### ISSUE TITLE
Eliminate orphans in Data.Profunctor.Product.Default

### ISSUE THREAD

**Issue by bitemyapp** [tomjaguarpaw/product-profunctors#46]
https://github.com/tomjaguarpaw/product-profunctors/blob/master/Data/Profunctor/Product/Default.hs#L1

Is there a reason this was necessary?

**Comment by tomjaguarpaw** [comment]
It was added by this change.  TH generates orphan instances:

https://github.com/tomjaguarpaw/product-profunctors/commit/92dc62981ccb2db8f98382db2f422b404c041798#diff-47fe8a80a95d7fb6acb9340ccd419ea8R35

I don't actually know why the definition of `Default` was moved into a separate module.  Perhaps @hesselink can comment.

**Comment by hesselink** [comment]
This was needed because the TH instances need the class, and the `Data.Profunctor.Product.Default` module imports the TH instances. Without it there would be a cyclic dependency. The alternative is .boot modules to allow the cyclic dependency, I guess. Since the pragma to disable this warning is limited to the one module, and the module containing the orphan is not exported (so you cannot get the class without the instance from outside the package), what is the issue with it?

**Comment by tomjaguarpaw** [comment]
Thanks @hesselink.  I think @bitemyapp just didn't see the TH and didn't realise there were any orphans in the module.

**Comment by bitemyapp** [comment]
I don't like it, but a morally-not-orphan where the ability to import without the instances is restricted seems acceptable to me.
